tmp_dir = "tmp"

[build]
cmd = "go build -o ./bin/main.exe ./cmd"
bin = "bin/main.exe"

include_dir = [".", "cmd", "internal"]
exclude_dir = ["tmp", "bin"]

include_ext = ["go"]
exclude_ext = ["swp"]

delay = 100
kill_signal = "ctrl+c"
kill_timeout = 500
