// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ai.sql

package database

import (
	"context"
)

const addAIFlags = `-- name: AddAIFlags :exec
INSERT INTO ai_flags (hashed_content, reason, confidence_score)
VALUES ($1, $2, $3)
`

type AddAIFlagsParams struct {
	HashedContent   string `json:"hashed_content"`
	Reason          string `json:"reason"`
	ConfidenceScore int32  `json:"confidence_score"`
}

func (q *Queries) AddAIFlags(ctx context.Context, arg AddAIFlagsParams) error {
	_, err := q.db.Exec(ctx, addAIFlags, arg.HashedContent, arg.Reason, arg.ConfidenceScore)
	return err
}

const getAIRules = `-- name: GetAIRules :many
SELECT rule
FROM ai_rules
WHERE is_active = TRUE
ORDER BY updated_at DESC
`

func (q *Queries) GetAIRules(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getAIRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var rule string
		if err := rows.Scan(&rule); err != nil {
			return nil, err
		}
		items = append(items, rule)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
