// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package database

import (
	"context"
)

const getAllChatFilePaths = `-- name: GetAllChatFilePaths :many
SELECT file_path FROM mentorship_chat_files
`

func (q *Queries) GetAllChatFilePaths(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getAllChatFilePaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var file_path string
		if err := rows.Scan(&file_path); err != nil {
			return nil, err
		}
		items = append(items, file_path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllMediaFilePaths = `-- name: GetAllMediaFilePaths :many
SELECT file_path FROM global_media_files
`

func (q *Queries) GetAllMediaFilePaths(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getAllMediaFilePaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var file_path string
		if err := rows.Scan(&file_path); err != nil {
			return nil, err
		}
		items = append(items, file_path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTaskFilePaths = `-- name: GetAllTaskFilePaths :many
SELECT file_path FROM task_files
`

func (q *Queries) GetAllTaskFilePaths(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getAllTaskFilePaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var file_path string
		if err := rows.Scan(&file_path); err != nil {
			return nil, err
		}
		items = append(items, file_path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllWorkspaceFilePaths = `-- name: GetAllWorkspaceFilePaths :many
SELECT file_path FROM solution_workspace_files
`

func (q *Queries) GetAllWorkspaceFilePaths(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getAllWorkspaceFilePaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var file_path string
		if err := rows.Scan(&file_path); err != nil {
			return nil, err
		}
		items = append(items, file_path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeChatFile = `-- name: RemoveChatFile :exec
DELETE FROM mentorship_chat_files WHERE file_path = $1
`

func (q *Queries) RemoveChatFile(ctx context.Context, filePath string) error {
	_, err := q.db.Exec(ctx, removeChatFile, filePath)
	return err
}

const removeMediaFile = `-- name: RemoveMediaFile :exec
DELETE FROM global_media_files WHERE file_path = $1
`

func (q *Queries) RemoveMediaFile(ctx context.Context, filePath string) error {
	_, err := q.db.Exec(ctx, removeMediaFile, filePath)
	return err
}

const removeTaskFile = `-- name: RemoveTaskFile :exec
DELETE FROM task_files WHERE file_path = $1
`

func (q *Queries) RemoveTaskFile(ctx context.Context, filePath string) error {
	_, err := q.db.Exec(ctx, removeTaskFile, filePath)
	return err
}

const removeWorkspaceFile = `-- name: RemoveWorkspaceFile :exec
DELETE FROM solution_workspace_files WHERE file_path = $1
`

func (q *Queries) RemoveWorkspaceFile(ctx context.Context, filePath string) error {
	_, err := q.db.Exec(ctx, removeWorkspaceFile, filePath)
	return err
}
