// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getAllTaskDrafts = `-- name: GetAllTaskDrafts :many
SELECT id, user_id, title, description, content, "contentText", category, deadline, updated_at, "uploadedFiles", visibility, price
FROM task_drafts
WHERE updated_at < $1
  AND json_array_length("uploadedFiles") > 0
`

func (q *Queries) GetAllTaskDrafts(ctx context.Context, updatedAt time.Time) ([]TaskDraft, error) {
	rows, err := q.db.Query(ctx, getAllTaskDrafts, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskDraft
	for rows.Next() {
		var i TaskDraft
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Content,
			&i.ContentText,
			&i.Category,
			&i.Deadline,
			&i.UpdatedAt,
			&i.UploadedFiles,
			&i.Visibility,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailbleTasks = `-- name: GetAvailbleTasks :many
SELECT id, title, description, content, price, poster_id, solver_id, visibility, category_id, payment_id, deadline, created_at, updated_at, task_status, assigned_at
FROM tasks
WHERE (task_status = 'ASSIGNED'
  OR task_status = 'IN_PROGRESS')
  AND assigned_at IS NOT NULL
LIMIT $1
`

func (q *Queries) GetAvailbleTasks(ctx context.Context, limit int32) ([]Task, error) {
	rows, err := q.db.Query(ctx, getAvailbleTasks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Content,
			&i.Price,
			&i.PosterID,
			&i.SolverID,
			&i.Visibility,
			&i.CategoryID,
			&i.PaymentID,
			&i.Deadline,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TaskStatus,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskCategories = `-- name: GetTaskCategories :many
SELECT name
FROM task_categories
`

func (q *Queries) GetTaskCategories(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getTaskCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFileFromTaskDraft = `-- name: RemoveFileFromTaskDraft :exec
UPDATE task_drafts
SET "uploadedFiles" = '[]'
WHERE id = $1
`

func (q *Queries) RemoveFileFromTaskDraft(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeFileFromTaskDraft, id)
	return err
}

const resetTaskInfo = `-- name: ResetTaskInfo :exec
UPDATE tasks
SET task_status = 'OPEN',
  assigned_at = NULL,
  updated_at = NOW(),
  solver_id = NULL
WHERE id = $1
`

func (q *Queries) ResetTaskInfo(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetTaskInfo, id)
	return err
}

const saveDraftTaskFiles = `-- name: SaveDraftTaskFiles :exec
UPDATE task_drafts
SET "uploadedFiles" = COALESCE("uploadedFiles", '[]'::jsonb) || $1::jsonb
WHERE user_id = $2
`

type SaveDraftTaskFilesParams struct {
	Column1 []byte    `json:"column_1"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) SaveDraftTaskFiles(ctx context.Context, arg SaveDraftTaskFilesParams) error {
	_, err := q.db.Exec(ctx, saveDraftTaskFiles, arg.Column1, arg.UserID)
	return err
}

const saveFileToWorkspaceDB = `-- name: SaveFileToWorkspaceDB :exec
INSERT INTO solution_workspace_files (
workspace_id,
uploaded_by_id,
file_name,
file_type,
file_size,
file_location,
file_path)
SELECT
  $1,
  $2,
  unnest($3::text[]),
  unnest($4::text[]),
  unnest($5::int[]),
  unnest($6::text[]),
  unnest($7::text[])
`

type SaveFileToWorkspaceDBParams struct {
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	UploadedByID uuid.UUID `json:"uploaded_by_id"`
	Column3      []string  `json:"column_3"`
	Column4      []string  `json:"column_4"`
	Column5      []int32   `json:"column_5"`
	Column6      []string  `json:"column_6"`
	Column7      []string  `json:"column_7"`
}

func (q *Queries) SaveFileToWorkspaceDB(ctx context.Context, arg SaveFileToWorkspaceDBParams) error {
	_, err := q.db.Exec(ctx, saveFileToWorkspaceDB,
		arg.WorkspaceID,
		arg.UploadedByID,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
	)
	return err
}
