// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteDraftTaskFile = `-- name: DeleteDraftTaskFile :exec
WITH definition AS (
  SELECT
    $1::text as target_path ,
    $2::uuid as target_user_id
)
UPDATE task_drafts
SET "uploadedFiles" = (
  SELECT COALESCE(jsonb_agg(elem), '[]'::jsonb)
  FROM jsonb_array_elements("uploadedFiles") AS elem
  WHERE elem->>'filePath' <> (SELECT target_path FROM definition)
)
WHERE user_id = (SELECT target_user_id FROM definition)
`

type DeleteDraftTaskFileParams struct {
	FilePath string    `json:"file_path"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteDraftTaskFile(ctx context.Context, arg DeleteDraftTaskFileParams) error {
	_, err := q.db.Exec(ctx, deleteDraftTaskFile, arg.FilePath, arg.UserID)
	return err
}

const getAllTaskDrafts = `-- name: GetAllTaskDrafts :many
SELECT id, user_id, title, description, content, "contentText", category, deadline, updated_at, "uploadedFiles", visibility, price
FROM task_drafts
WHERE updated_at < $1
  AND json_array_length("uploadedFiles") > 0
`

func (q *Queries) GetAllTaskDrafts(ctx context.Context, updatedAt time.Time) ([]TaskDraft, error) {
	rows, err := q.db.Query(ctx, getAllTaskDrafts, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskDraft
	for rows.Next() {
		var i TaskDraft
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Content,
			&i.ContentText,
			&i.Category,
			&i.Deadline,
			&i.UpdatedAt,
			&i.UploadedFiles,
			&i.Visibility,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailbleTasks = `-- name: GetAvailbleTasks :many
SELECT id, title, description, content, price, poster_id, solver_id, visibility, category_id, payment_id, deadline, created_at, updated_at, task_status, assigned_at
FROM tasks
WHERE (task_status = 'ASSIGNED'
  OR task_status = 'IN_PROGRESS')
  AND assigned_at IS NOT NULL
LIMIT $1
`

func (q *Queries) GetAvailbleTasks(ctx context.Context, limit int32) ([]Task, error) {
	rows, err := q.db.Query(ctx, getAvailbleTasks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Content,
			&i.Price,
			&i.PosterID,
			&i.SolverID,
			&i.Visibility,
			&i.CategoryID,
			&i.PaymentID,
			&i.Deadline,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TaskStatus,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskCategories = `-- name: GetTaskCategories :many
SELECT name
FROM task_categories
`

func (q *Queries) GetTaskCategories(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getTaskCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFileFromTaskDraft = `-- name: RemoveFileFromTaskDraft :exec
UPDATE task_drafts
SET "uploadedFiles" = '[]'
WHERE id = $1
`

func (q *Queries) RemoveFileFromTaskDraft(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeFileFromTaskDraft, id)
	return err
}

const resetTaskInfo = `-- name: ResetTaskInfo :exec
UPDATE tasks
SET task_status = 'OPEN',
  assigned_at = NULL,
  updated_at = NOW(),
  solver_id = NULL
WHERE id = $1
`

func (q *Queries) ResetTaskInfo(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetTaskInfo, id)
	return err
}

const saveDraftTaskFiles = `-- name: SaveDraftTaskFiles :exec
UPDATE task_drafts
SET "uploadedFiles" = COALESCE("uploadedFiles", '[]'::jsonb) || $1::jsonb
WHERE user_id = $2
`

type SaveDraftTaskFilesParams struct {
	Column1 []byte    `json:"column_1"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) SaveDraftTaskFiles(ctx context.Context, arg SaveDraftTaskFilesParams) error {
	_, err := q.db.Exec(ctx, saveDraftTaskFiles, arg.Column1, arg.UserID)
	return err
}
